let studies=[];
const feed=document.querySelector('#feed');
const journalFeed=document.querySelector('#journal-feed');
const search=document.querySelector('#search');
const category=document.querySelector('#category');
const design=document.querySelector('#design');
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function populate(select, values){
  [...new Set(values.filter(Boolean))].sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option)});
}
function roleClass(role=''){return role.toLowerCase().replace(/[^a-z]+/g,'-').replace(/^-|-$/g,'')}

function renderJournal(){
  const panels=studies.filter(s=>s.panel);
  document.querySelector('#panel-count').textContent=`${panels.length} active review${panels.length===1?'':'s'}`;
  journalFeed.innerHTML=panels.length?panels.map((s,index)=>`
    <article class="journal-card">
      <header class="journal-header">
        <div><p class="eyebrow">JOURNAL CLUB ${String(index+1).padStart(2,'0')}</p><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.journal)} · ${escapeHtml(s.publication_date||'Date unavailable')}</p></div>
        <span class="verdict">${escapeHtml(s.panel.director?.verdict||'Review')}</span>
      </header>
      <div class="research-question"><span>Question before the team</span><strong>${escapeHtml(s.panel.question)}</strong></div>
      <div class="discussion">
        ${(s.panel.members||[]).map(m=>`<section class="voice ${roleClass(m.role)}"><div class="avatar">${escapeHtml(m.role.split(' ').map(w=>w[0]).join('').slice(0,2))}</div><div><p><b>${escapeHtml(m.role)}</b><span>${escapeHtml(m.stance)}</span></p><blockquote>${escapeHtml(m.comment)}</blockquote></div></section>`).join('')}
      </div>
      <section class="director-note">
        <div><p class="eyebrow">RESEARCH DIRECTOR</p><h4>${escapeHtml(s.panel.director?.consensus)}</h4></div>
        <dl><div><dt>Where the team disagrees</dt><dd>${escapeHtml(s.panel.director?.disagreement)}</dd></div><div><dt>Question still open</dt><dd>${escapeHtml(s.panel.director?.next_question)}</dd></div></dl>
      </section>
      <footer class="source-row"><span>Generated by ${escapeHtml(s.panel.generated_by||'agent')}</span><a href="${s.url}" target="_blank" rel="noopener">Read the PubMed record ↗</a></footer>
    </article>`).join(''):'<div class="empty">No journal club has been generated yet. Run the refresh workflow with an optional OpenAI API key.</div>';
}

function renderLibrary(){
  const q=search.value.trim().toLowerCase();
  const visible=studies.filter(s=>{const haystack=[s.title,s.abstract,s.journal,s.practitioner_takeaway,...(s.categories||[])].join(' ').toLowerCase();return(!q||haystack.includes(q))&&(category.value==='all'||s.categories.includes(category.value))&&(design.value==='all'||s.study_design===design.value)});
  document.querySelector('#result-count').textContent=`${visible.length} result${visible.length===1?'':'s'}`;
  feed.innerHTML=visible.length?visible.map(s=>`
    <article class="study"><div class="study-meta"><strong>${escapeHtml(s.study_design)}</strong><p>${escapeHtml(s.publication_date||'Date unavailable')}</p><p>Confidence<br><b>${escapeHtml(s.evidence_confidence)}</b></p><p>Clinical relevance<br><b>${escapeHtml(s.clinical_relevance)}</b></p></div><div><div>${(s.categories||[]).map(c=>`<span class="pill">${escapeHtml(c)}</span>`).join('')}</div><h3>${escapeHtml(s.title)}</h3><p class="journal">${escapeHtml(s.journal)}${s.authors?.length?' · '+escapeHtml(s.authors.join(', ')):''}</p><div class="takeaway"><b>Practitioner takeaway</b>${escapeHtml(s.practitioner_takeaway)}</div><a href="${s.url}" target="_blank" rel="noopener">Review source on PubMed ↗</a></div></article>`).join(''):'<div class="empty">No studies match these filters.</div>';
}

document.querySelectorAll('.nav-button').forEach(button=>button.addEventListener('click',()=>{
  document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b===button));
  document.querySelector('#journal-view').classList.toggle('hidden',button.dataset.view!=='journal');
  document.querySelector('#library-view').classList.toggle('hidden',button.dataset.view!=='library');
}));

fetch('studies.json').then(r=>r.json()).then(data=>{
  studies=data.studies||[];
  document.querySelector('#study-count').textContent=data.study_count||0;
  document.querySelector('#updated').textContent=`Updated ${data.generated_on} · ${data.panel_count||0} team reviews`;
  populate(category,studies.flatMap(s=>s.categories||[]));populate(design,studies.map(s=>s.study_design));renderJournal();renderLibrary();
}).catch(()=>{journalFeed.innerHTML='<div class="empty">The evidence feed has not been generated yet. Run the GitHub workflow first.</div>'});
[search,category,design].forEach(el=>el.addEventListener('input',renderLibrary));
